### ISSUE TITLE
Atualização.

### ISSUE THREAD

**Issue by luizmucman** [mrgasparini/ClashOfCars-Bot#1]
Mudou a rota de login. E agora ele pede uma "publickey"
nova rota https://api.clashofcars.io/api/auth/player/login/security

e a publicKey = "{ \"message\":\"Sign this message to prove your authenticity!\",\"publicKey\":\"BnUSS4QVYeedttZvnDXURBLiHEci6pxk9yJ7ppFdK26z\",\"signedMessage\":{ \"type\":\"Buffer\",\"data\":[151,80,38,53,109,254,126,223,81,24,192,80,176,159,54,48,124,110,235,122,63,197,87,118,149,100,95,7,181,134,193,246,207,169,145,141,43,26,6,244,71,246,224,91,242,12,118,83,135,183,237,215,24,228,34,229,65,255,154,55,200,161,145,4]} }";

**Comment by mrgasparini** [comment]
Fala cara! Valeu pelo aviso!! Eu subi as atualizações hj com algumas otimizações aos horários dos refuels. 

Demorei pq estava um pouco sem tempo no fim de semana!
